# -*- coding: utf-8 -*-
"""linear_regression_hours_scores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1puvnY1KLZHgYCXyeVE2ls51VLagUetc2

# LOAD DATA
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('datasets/score_updated.csv')
df.head()

df.info()

df = df.loc[:, ['Hours', 'Scores']]
df

"""# DATA PROCESSING"""

x = df['Hours'].values
y = df['Scores'].values

n = len(x)

"""# MODELING"""

sum_x = np.sum(x)
sum_y = np.sum(y)
sum_xy = np.sum(x*y)
sum_x2 = np.sum(x*x)

a = (sum_y * sum_x2 - sum_x * sum_xy) / (n * sum_x2 - sum_x**2)
b = (n * sum_xy - sum_x * sum_y) / (n * sum_x2 - sum_x**2)

new_hours = 2.5
score_pred = a + b * new_hours
print("Waktu belajar:", new_hours, "| Score yang didapatkan:", score_pred)

"""# EVALUATION"""

y_pred = a + b * x

SS_res = np.sum((y - y_pred)**2)
SS_tot = np.sum((y - np.mean(y))**2)
r2 = 1 - SS_res / SS_tot

mae = np.mean(np.abs(y - y_pred))
mse = np.mean((y - y_pred)**2)
rmse = np.sqrt(mse)

print("Model Performance:")
print("MAE: ", mae)
print("MSE: ", mse)
print("RMSE: ", rmse)
print("R-squared: ", r2)

"""# VISUALIZATION"""

plt.title("Linear Regression: Study Hours vs Scores")
plt.scatter(x, y, color='blue', label='Data Points')
plt.plot(x, y_pred, color='red', label='Regression Line')
plt.scatter(new_hours, score_pred, color='green', label='Prediction')
plt.xlabel("Hours")
plt.ylabel("Scores")
plt.grid(True)
plt.legend()
plt.show()

